# .github/workflows/ci.yml

name: Pipeline de CI para Microsserviço de Produção

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          # Precisamos de um fetch mais profundo para uma análise correta do SonarCloud
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
        env:
          MONGO_URI: "mongodb://localhost:27017/testdb"

      # --- NOVO PASSO ADICIONADO ---
      # Este passo envia os resultados para o SonarCloud
      - name: Análise SonarCloud
        # Roda este passo apenas se o evento não for de um fork (por segurança)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: SonarSource/sonarcloud-github-action@master
        env:
          # Token que configuramos nos segredos do GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_SECURITY_TOKEN }}
          # Segredo padrão do GitHub Actions, não precisa configurar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
