# .github/workflows/ci.yml

name: Pipeline de CI para Microsserviço de Produção

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
        env:
          MONGO_URI: "mongodb://localhost:27017/testdb"

      - name: Análise SonarCloud
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECURITY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job para construir e publicar a imagem Docker
  deploy:
    # Garante que este job só rode se o de build-e-test passar
    needs: build-e-test
    # Roda apenas em pushes para a branch main, não em Pull Requests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: brunoadpaixao/fiap-tech-challenge-4-producao-de-pedidos
