# .github/workflows/ci.yml

name: Pipeline de CI para Microsserviço de Produção

# Define os gatilhos (triggers) que iniciam a pipeline
on:
  push:
    branches: [main] # Roda quando há um push na branch main
  pull_request:
    branches: [main] # Roda quando um Pull Request é aberto para a main

jobs:
  # Define um "job" (trabalho) chamado "build-e-test"
  build-e-test:
    # Define o tipo de máquina virtual que será usada para rodar o job
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clona o seu repositório para dentro da máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Node.js na versão 18
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm" # Habilita o cache para acelerar a instalação de dependências

      # Passo 3: Instala todas as dependências do projeto
      - name: Instalar dependências
        run: npm install

      # Passo 4: Roda os testes (e a verificação de cobertura)
      # O comando "npm test" já está configurado no seu package.json para rodar "jest --coverage"
      - name: Rodar testes
        run: npm test
        env:
          MONGO_URI: "mongodb://localhost:27017/testdb"
